### PR TITLE
chore: fix mistake in permissions example

### PR DESCRIPTION
**Pull request by schalkneethling**
The permissions example was not quite correct. This fixes the blunder :)

### CODE REVIEW

**Comment by KobayashiComputing** [comment]
Two thoughts... 
First, for a directory, it is my understanding that an 'x' in the permissions settings means "search" instead of "execute." 
Second, a permissions field of drwxr-xr-x indicates that both the group and other access for the directory is read and search (with no write capability to the directory). 
I, of course, could be missing something...

**Comment by schalkneethling** [comment]
> drwxr-xr-x

Ah, interesting. I thought the above breaks down as follows:

> d - in this case, directory
> rwxr - owner
> xr - group
> x - other or world

**Comment by KobayashiComputing** [comment]
Ah, no...

It breaks down like the following:

d : Directory
rwx : user's permissions
r-x  : group's permissions
r-x  : other's permissions

Each entity has 3 positions (rwx).

**Comment by schalkneethling** [comment]
> Ah, no...
> 
> It breaks down like the following:
> 
> d : Directory rwx : user's permissions r-x : group's permissions r-x : other's permissions
> 
> Each entity has 3 positions (rwx).

Ah, that explains the confusion with the first entry, which seems to have four. Thanks for clearing that up.

**Pull request closed without merging**
